// Pure capability-broker logic — envelope construction, scoping decisions, and
// the M1 in-process `ping` no-op resolver. This module MUST stay free of any
// `electron` import so it can be unit-tested under Vitest's node environment.
// The IPC wiring that calls into these functions lives in
// `frontendPluginManager.ts`.

import { resolveWsType } from './capabilityMap'
import type { WsResponse } from '../../shared/wsClient'

/** A capability call as it arrives from a plugin view over IPC. */
export interface CapabilityCall {
  /** The manifest id of the calling plugin (injected by the manager, not the view). */
  pluginId: string
  /** Capability namespace, e.g. `ping`, `fs`, `git`. */
  ns: string
  /** Method within the namespace. */
  method: string
  /** Opaque, plugin-supplied arguments. */
  args: unknown
  /** Correlation id generated by the plugin preload. */
  reqId: string
}

/** The response envelope returned to the plugin view. */
export interface CapabilityResponse {
  reqId: string
  ok: boolean
  result?: unknown
  error?: { code: CapabilityErrorCode; message?: string }
}

export type CapabilityErrorCode = 'CAP_DENIED' | 'UNKNOWN' | 'BAD_REQUEST' | 'BACKEND_ERROR'

/**
 * Namespaces the host grants without an explicit `requires` declaration. `ping`
 * is the M1 built-in used to prove the IPC envelope round-trips end to end.
 */
export const BUILTIN_CAPABILITIES: readonly string[] = ['ping']

/**
 * Scoping decision: may a plugin whose manifest declares `requires` call `ns`?
 * Built-in namespaces (see {@link BUILTIN_CAPABILITIES}) are always allowed;
 * everything else must be listed in the plugin's `requires`.
 */
export function isCapabilityAllowed(requires: readonly string[], ns: string): boolean {
  if (BUILTIN_CAPABILITIES.includes(ns)) return true
  return requires.includes(ns)
}

/** Build a success envelope. */
export function buildSuccess(reqId: string, result: unknown): CapabilityResponse {
  return { reqId, ok: true, result }
}

/** Build an error envelope. */
export function buildError(
  reqId: string,
  code: CapabilityErrorCode,
  message?: string
): CapabilityResponse {
  return { reqId, ok: false, error: message ? { code, message } : { code } }
}

/**
 * Validate an untrusted IPC payload into a {@link CapabilityCall}. Returns
 * `null` when the shape is wrong so the caller can reject with `BAD_REQUEST`.
 * `pluginId` is authoritative from the manager, so it is not read from the
 * payload here — the caller supplies it.
 */
export function parseCapabilityCall(raw: unknown, pluginId: string): CapabilityCall | null {
  if (typeof raw !== 'object' || raw === null) return null
  const r = raw as Record<string, unknown>
  if (typeof r.ns !== 'string' || r.ns.length === 0) return null
  if (typeof r.method !== 'string' || r.method.length === 0) return null
  if (typeof r.reqId !== 'string' || r.reqId.length === 0) return null
  return { pluginId, ns: r.ns, method: r.method, args: r.args, reqId: r.reqId }
}

/**
 * Resolve a capability call to its response, given the calling plugin's
 * declared `requires`. This is the whole M1 broker surface:
 *   - not allowed        → `CAP_DENIED`
 *   - `ping`/any method  → `{ pong: true, echo: args }`
 *   - anything else       → `UNKNOWN`
 * M2 replaces the `ping` branch with a dispatch to the backend WS host.
 */
export function resolveCapabilityCall(
  call: CapabilityCall,
  requires: readonly string[]
): CapabilityResponse {
  if (!isCapabilityAllowed(requires, call.ns)) {
    return buildError(call.reqId, 'CAP_DENIED', `capability '${call.ns}' not granted`)
  }
  if (call.ns === 'ping') {
    return buildSuccess(call.reqId, { pong: true, echo: call.args })
  }
  return buildError(call.reqId, 'UNKNOWN', `no handler for '${call.ns}.${call.method}'`)
}

/**
 * Host-implemented capabilities: `(ns.method)` calls the manager services in
 * the main process itself instead of dispatching to the backend WS. Scoping
 * still applies (the ns must be granted by the manifest). `open_in_editor`
 * routes a file to the mini-IDE plugin window — with the main-side
 * openMiniIdeEditor fallback chain (OS default app when the mini-IDE is not
 * installed/available).
 */
export const HOST_CAPABILITIES: Readonly<Record<string, string>> = {
  'ui.open_in_editor': 'open_in_editor',
  // Shell-level actions the Git window's worktree/remote cards need (GitPane
  // parity): open an http(s) URL in the default browser, reveal a path in the
  // OS file manager, open a workspace in a new main window, and a native
  // directory picker (async result).
  'ui.open_external': 'open_external',
  'ui.reveal_path': 'reveal_path',
  'ui.open_workspace': 'open_workspace',
  'ui.pick_folder': 'pick_folder',
}

/**
 * A decision about how to service a capability call. `respond` carries a
 * ready-made envelope (deny / built-in ping / unknown); `backend` names the
 * backend WS message type the manager should dispatch and await; `host` names
 * a main-process action from {@link HOST_CAPABILITIES}.
 */
export type CapabilityPlan =
  | { kind: 'respond'; response: CapabilityResponse }
  | { kind: 'backend'; wsType: string }
  | { kind: 'host'; action: string }

/**
 * M2 dispatch planner. Enforces scoping first (an un-granted namespace is
 * denied here and never reaches the backend), then routes:
 *   - `ping`            → in-process success (M1 built-in)
 *   - mapped `(ns,m)`   → `backend` with the WS type from {@link resolveWsType}
 *   - anything else     → `UNKNOWN`
 */
export function planCapabilityCall(
  call: CapabilityCall,
  requires: readonly string[]
): CapabilityPlan {
  if (!isCapabilityAllowed(requires, call.ns)) {
    return {
      kind: 'respond',
      response: buildError(call.reqId, 'CAP_DENIED', `capability '${call.ns}' not granted`),
    }
  }
  if (call.ns === 'ping') {
    return { kind: 'respond', response: buildSuccess(call.reqId, { pong: true, echo: call.args }) }
  }
  const hostAction = HOST_CAPABILITIES[`${call.ns}.${call.method}`]
  if (hostAction) {
    return { kind: 'host', action: hostAction }
  }
  const wsType = resolveWsType(call.ns, call.method)
  if (!wsType) {
    return {
      kind: 'respond',
      response: buildError(call.reqId, 'UNKNOWN', `no handler for '${call.ns}.${call.method}'`),
    }
  }
  return { kind: 'backend', wsType }
}

/** Map a backend WS response envelope into the plugin-facing capability
 *  envelope, preserving the correlation id the plugin is awaiting. */
export function backendResponseToCapability(
  reqId: string,
  resp: WsResponse
): CapabilityResponse {
  if (resp.ok) return buildSuccess(reqId, resp.payload)
  return buildError(reqId, 'BACKEND_ERROR', resp.error?.message ?? 'backend request failed')
}
